Repository MicrosoftDocs/azure-aks-docs, pull requests merged in 2024-09, with the labels that each got.

#9 Update auto-upgrade-cluster.md
  articles/aks/auto-upgrade-cluster.md
Labels: do-not-merge, Change sent to author, azure-kubernetes-service/svc, aq-pr-triaged, aks-upgrade/subsvc

#35 Update azure-blob-csi.md
  articles/aks/azure-blob-csi.md
Labels: do-not-merge, Change sent to author, azure-kubernetes-service/svc, aq-pr-triaged, aks-storage/subsvc

#38 Fix grammar in use-managed-identity.md
  articles/aks/use-managed-identity.md
Labels: do-not-merge, Change sent to author, azure-kubernetes-service/svc, aks-security/subsvc

#34 Update private-clusters.md
  articles/aks/private-clusters.md
Labels: ready-to-merge, Change sent to author, azure-kubernetes-service/svc, aq-pr-triaged, qualifies-for-auto-merge

#42 Replace cluster with resource group
  articles/aks/faq.yml
Labels: do-not-merge, review-team-triage, needs-human-review

#46 Update scale-cluster.md
  articles/aks/scale-cluster.md
Labels: ready-to-merge, Change sent to author, azure-kubernetes-service/svc, aq-pr-triaged, qualifies-for-auto-merge

#47 Format Newline for `--issuer` Argument in CNPG + AKS Guide
  articles/aks/deploy-postgresql-ha.md
Labels: do-not-merge, Change sent to author, azure-kubernetes-service/svc, aq-pr-triaged, qualifies-for-auto-merge
